
name: Build components

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-rockylinux87:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    with:
      image: rockylinux:8.7
      dpcpp-version: intel/2024.0
      level-zero-version: public/1.15.1
      pre-cmd: |
        unset no_proxy
        unset NO_PROXY
        dnf update -y
        dnf install -y 'dnf-command(config-manager)'
        dnf config-manager --add-repo https://repositories.intel.com/graphics/rhel/8.6/flex/intel-graphics.repo
        dnf install -y intel-ocloc
        dnf --enablerepo=powertools install -y ninja-build
      cmd: |
        module load cmake/3.25.3
        module load impi/latest
        export CC=icx
        export CXX=icpx
        export CXXFLAGS="-fhonor-infinities -fhonor-nans"
        export LDFLAGS="-static-intel"
        cmake -L -S . -B build -G Ninja -DCMAKE_INSTALL_PREFIX=install -DOSPRAY_ENABLE_MODULE_MPI=OFF -DENABLE_GPU_SUPPORT=ON
        cmake --build build --config Release

  build-macos:
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/macos.yml@main
    with:
      cmd: |
        export CXXFLAGS='-stdlib=libc++'
        export MACOSX_DEPLOYMENT_TARGET=11.0
        mkdir build
        cmake -L -S . -B build -DCMAKE_INSTALL_PREFIX=install
        cmake --build build --config Release

  build-windows:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows_gpu.yml@main
    with:
      dpcpp-version: oneAPI/compiler/2024.0
      level-zero-version: public/1.15.1
      ocloc-version: 77a13ae6-6100-4ddc-b069-0086ff44730c/ocloc_win_101.5082
      cmd: |
        call "C:\Program Files (x86)\Intel\oneAPI\mpi\latest\env\vars.bat"
        set CXX=icx.exe
        set CC=icx.exe
        cmake -L -S . -B build -G Ninja -DCMAKE_INSTALL_PREFIX=install -DOSPRAY_ENABLE_MODULE_MPI=OFF -DENABLE_GPU_SUPPORT=ON
        cmake --build build --config Release
      shell: cmd

